SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS borrowing;
DROP TABLE IF EXISTS reservation;
DROP TABLE IF EXISTS review;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS book_author;
DROP TABLE IF EXISTS book_category;
DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS school;
DROP TABLE IF EXISTS language;
DROP TABLE IF EXISTS author;
DROP TABLE IF EXISTS category;

SET FOREIGN_KEY_CHECKS = 1;
 


